server:
  port: 9000
spring:
  application.name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka
feign:
  hystrix:
    enabled: true
user-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule/